#![cfg(test)]
extern crate std;

use soroban_sdk::{
    crypto::bn254::{Fr, Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
    testutils::Address as _,
    Address, BytesN, Env, Vec,
};

use crate::{AgeVerifier, AgeVerifierClient, AgeVerifierError, Groth16Proof, StoredVk};

// ── Byte-conversion helpers ───────────────────────────────────────────────────
// Encode BN254 field elements from decimal strings to big-endian 32-byte arrays.
// Uses primitive arithmetic only — no ark dependency.

fn dec_to_be32(decimal: &str) -> [u8; 32] {
    // Parse decimal string into 32-byte big-endian using u128 arithmetic in chunks
    let mut result = [0u8; 32];
    let remaining = decimal.trim();
    // Accumulate digit-by-digit: result = result * 10 + digit
    for ch in remaining.chars() {
        let d = (ch as u8) - b'0';
        let mut carry = d as u16;
        for byte in result.iter_mut().rev() {
            let val = (*byte as u16) * 10 + carry;
            *byte = (val & 0xff) as u8;
            carry = val >> 8;
        }
    }
    result
}

// G1 point: x BE (32) || y BE (32) = 64 bytes (EIP-196 encoding)
fn g1_bytes(x: &str, y: &str) -> [u8; 64] {
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&dec_to_be32(x));
    out[32..].copy_from_slice(&dec_to_be32(y));
    out
}

// G2 point: x.c1 BE || x.c0 BE || y.c1 BE || y.c0 BE = 128 bytes (Ethereum encoding)
// snarkjs format: [[x.c0, x.c1], [y.c0, y.c1]] → we pass (x0=c0, x1=c1, y0=c0, y1=c1)
fn g2_bytes(x0: &str, x1: &str, y0: &str, y1: &str) -> [u8; 128] {
    let mut out = [0u8; 128];
    out[..32].copy_from_slice(&dec_to_be32(x1));   // x.c1
    out[32..64].copy_from_slice(&dec_to_be32(x0)); // x.c0
    out[64..96].copy_from_slice(&dec_to_be32(y1)); // y.c1
    out[96..].copy_from_slice(&dec_to_be32(y0));   // y.c0
    out
}

fn fr_from_u32(env: &Env, value: u32) -> Fr {
    let mut b = [0u8; 32];
    b[28..].copy_from_slice(&value.to_be_bytes());
    Fr::from_bytes(BytesN::from_array(env, &b))
}

/// Fr from a 32-byte big-endian hex string (without 0x prefix)
fn fr_from_hex(env: &Env, hex: &str) -> Fr {
    let mut b = [0u8; 32];
    for i in 0..32 {
        b[i] = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    Fr::from_bytes(BytesN::from_array(env, &b))
}

fn test_issuer_pubkey(env: &Env) -> BytesN<32> {
    // Generated by: node scripts/sign_commitment.js keygen
    let hex = "c06840fcf54853ed731c04eb3b4eb8f21bf4d5b23773f8c64b544a98a58d0571";
    let mut b = [0u8; 32];
    for i in 0..32 { b[i] = u8::from_str_radix(&hex[i*2..i*2+2], 16).unwrap(); }
    BytesN::from_array(env, &b)
}

fn test_issuer_sig(env: &Env) -> BytesN<64> {
    // Issuer Ed25519 signature over commitment bytes
    // commitment: 0x1d130c124dcd8f309b892bfb0c46387cc3de5cbe84cf5aa0e1a5644d617ccde7
    // Generated by: ISSUER_PRIVKEY=... node scripts/sign_commitment.js sign <commitment>
    let hex = "35405f0263d5f5b04ae704d29ce57f99f191eb760035d718cc7ad8ef13870a43035ef5da9dd8ced264cc238644343db48c74ff8bf350a8b951e7f1d641b3820c";
    let mut b = [0u8; 64];
    for i in 0..64 { b[i] = u8::from_str_radix(&hex[i*2..i*2+2], 16).unwrap(); }
    BytesN::from_array(env, &b)
}

fn null(env: &Env) -> BytesN<32> {
    BytesN::from_array(env, &[0u8; 32])
}

// ── VK — from circuits/age_verifier/verification_key.json ─────────────────────
// Circuit: age_verifier.circom with addressHash + Poseidon commitment
// Generated by: make circuits && node scripts/convert_vk.js circuits/age_verifier/verification_key.json

fn test_vk(env: &Env) -> StoredVk {
    let alpha = g1_bytes(
        "20491192805390485299153009773594534940189261866228447918068658471970481763042",
        "9383485363053290200918347156157836566562967994039712273449902621266178545958",
    );
    let beta = g2_bytes(
        "6375614351688725206403948262868962793625744043794305715222011528459656738731",
        "4252822878758300859123897981450591353533073413197771768651442665752259397132",
        "10505242626370262277552901082094356697409835680220590971873171140371331206856",
        "21847035105528745403288232691147584728191162732299865338377159692350059136679",
    );
    let gamma = g2_bytes(
        "10857046999023057135944570762232829481370756359578518086990519993285655852781",
        "11559732032986387107991004021392285783925812861821192530917403151452391805634",
        "8495653923123431417604973247489272438418190587263600148770280649306958101930",
        "4082367875863433681332203403145435568316851327593401208105741076214120093531",
    );
    let delta = g2_bytes(
        "15919018573284737069972230958205022818963581109243504510967879490221101242884",
        "15532268796691154359348013205550925671553051401347655552272416132461655383108",
        "14025076609898679148872996043230091744148975181434783376123922426618495548662",
        "18046768686138100873220567104985609381591871206223808005724112887945770159840",
    );

    // IC[0] = constant term; IC[1..3] = isOldEnough, commitment, addressHash
    let ic0 = g1_bytes(
        "2655087538273877345819143174661243608012399070276628086226135137656939843302",
        "13127731123305705959139717556827383278633878361252582949702408122522240514816",
    );
    let ic1 = g1_bytes(
        "5882250721570124199124901368086768931775798672501110701615593612287942175987",
        "20825453877899146665391436699744561873881452151871490248682344283789418118206",
    );
    let ic2 = g1_bytes(
        "2407564347866405887529756433386719948048029489450641644267787994271782176753",
        "17036477037128491068615625730470007937295245010871437272882495132781601314187",
    );
    let ic3 = g1_bytes(
        "5733623821438223010686721586698323430664103360860997626802642125826813486658",
        "21739566915060185764918798104513033583488765356435643045480144030635571784081",
    );

    let mut ic_vec: Vec<BytesN<64>> = Vec::new(env);
    ic_vec.push_back(BytesN::from_array(env, &ic0));
    ic_vec.push_back(BytesN::from_array(env, &ic1));
    ic_vec.push_back(BytesN::from_array(env, &ic2));
    ic_vec.push_back(BytesN::from_array(env, &ic3));

    StoredVk {
        alpha: BytesN::from_array(env, &alpha),
        beta:  BytesN::from_array(env, &beta),
        gamma: BytesN::from_array(env, &gamma),
        delta: BytesN::from_array(env, &delta),
        ic:    ic_vec,
    }
}

// ── Proof — real values from circuit ──────────────────────────────────────────
// Input: birthDate=946684800 (2000-01-01), minAge=18, currentDate=1750715415,
//        addressHash=7235385670867189986095619048171703511367991620015764553014688608656441233342
//        (Stellar address: GCQSYAFC7AACW4A2RM66V7NFT3P64ND47EK5U57GYBGBEIFHRBH4C6C6)
// Generated by: node scripts/generate_proof.js 946684800 18 <addressHash>

fn test_proof(env: &Env) -> (Groth16Proof, Vec<Fr>) {
    let a = g1_bytes(
        "9968157170029525761245643167925000498211886364934073555937536743905165461178",
        "4704466322600006685391530061158712278250684932367019217358165903780133865657",
    );
    let b = g2_bytes(
        "20953022430292064317089072676021598417527985325082880926433897423210637743400",
        "12865257763690403874784740407699031188193292042052823371847829621768125738699",
        "9189858025137492896999133819051785506820228390897649889253106781995940231842",
        "14373060122668685670137340006107103380803481020705507683497755146571604463179",
    );
    let c = g1_bytes(
        "12666829211921098530370139545799020613236545868456546828116104744718300858886",
        "2530215812214542249134761896509348820303697605204351640022582167252957868346",
    );

    let proof = Groth16Proof {
        a: G1Affine::from_bytes(BytesN::from_array(env, &a)),
        b: G2Affine::from_bytes(BytesN::from_array(env, &b)),
        c: G1Affine::from_bytes(BytesN::from_array(env, &c)),
    };

    // Public signals: [isOldEnough=1, commitment, addressHash]
    let mut inputs: Vec<Fr> = Vec::new(env);
    inputs.push_back(fr_from_u32(env, 1));
    inputs.push_back(fr_from_hex(env, "1d130c124dcd8f309b892bfb0c46387cc3de5cbe84cf5aa0e1a5644d617ccde7"));
    inputs.push_back(fr_from_hex(env, "0fff154a546b4af2f19a6cc7792195c87598c41fa8ae2632f4a63164d7884fbe"));

    (proof, inputs)
}

fn setup(env: &Env) -> AgeVerifierClient<'_> {
    AgeVerifierClient::new(env, &env.register(AgeVerifier {}, ()))
}

// Initialize with fee=0 and dummy addresses — no USDC token needed in tests.
fn init(env: &Env, client: &AgeVerifierClient<'_>) {
    let admin    = Address::generate(env);
    let treasury = Address::generate(env);
    let usdc_tok = Address::generate(env);
    client.initialize(&test_vk(env), &test_issuer_pubkey(env), &admin, &treasury, &usdc_tok, &0i128);
}

// ── Tests ─────────────────────────────────────────────────────────────────────
// Structure is correct. Values marked TODO need regeneration after make circuits.

#[test]
fn test_double_initialize_rejected() {
    let env = Env::default();
    let client = setup(&env);
    init(&env, &client);
    let admin    = Address::generate(&env);
    let treasury = Address::generate(&env);
    let usdc_tok = Address::generate(&env);
    let result = client.try_initialize(&test_vk(&env), &test_issuer_pubkey(&env), &admin, &treasury, &usdc_tok, &0i128);
    assert_eq!(result, Err(Ok(AgeVerifierError::AlreadyInitialized)));
}

#[test]
fn test_verify_before_initialize_rejected() {
    let env = Env::default();
    env.mock_all_auths();
    let client = setup(&env);
    let (proof, inputs) = test_proof(&env);
    let caller = Address::generate(&env);
    let result = client.try_verify(&caller, &proof, &inputs, &null(&env), &test_issuer_sig(&env));
    assert_eq!(result, Err(Ok(AgeVerifierError::NotInitialized)));
}

#[test]
fn test_wrong_input_count_rejected() {
    let env = Env::default();
    env.mock_all_auths();
    let client = setup(&env);
    init(&env, &client);

    // Pass 1 input instead of required 3
    let mut bad_inputs: Vec<Fr> = Vec::new(&env);
    bad_inputs.push_back(fr_from_u32(&env, 1));

    let a_bytes = [0u8; 64];
    let b_bytes = [0u8; 128];
    let dummy_proof = Groth16Proof {
        a: G1Affine::from_bytes(BytesN::from_array(&env, &a_bytes)),
        b: G2Affine::from_bytes(BytesN::from_array(&env, &b_bytes)),
        c: G1Affine::from_bytes(BytesN::from_array(&env, &a_bytes)),
    };

    let caller = Address::generate(&env);
    let result = client.try_verify(&caller, &dummy_proof, &bad_inputs, &null(&env), &test_issuer_sig(&env));
    assert_eq!(result, Err(Ok(AgeVerifierError::MalformedPublicInputs)));
}

// TODO: add test_replay_rejected after deploy + full proof round-trip validated.
// Flow: verify() once → succeed → verify() again with same nullifier → NullifierUsed error.

// TODO: after make circuits, add:
//
// #[test]
// fn test_valid_proof_accepted() {
//     let env = Env::default();
//     let client = setup(&env);
//     client.initialize(&test_vk(&env), &REAL_ISSUER_PUBKEY);
//     let (proof, inputs) = test_proof(&env);
//     let result = client.verify(&proof, &inputs, &null(&env), &REAL_ISSUER_SIG);
//     assert_eq!(result, Ok(true));
// }
//
// #[test]
// fn test_age_constraint_fails_for_minor() { ... }
//
// #[test]
// fn test_invalid_issuer_sig_rejected() { ... }
